// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZYlyW44h-2Y836hSHRArqq1EbDjh5-yM',
    appId: '1:128483735486:web:5b9593cd30cc627a6c2bef',
    messagingSenderId: '128483735486',
    projectId: 'eventhub-b088e',
    authDomain: 'eventhub-b088e.firebaseapp.com',
    storageBucket: 'eventhub-b088e.appspot.com',
    measurementId: 'G-72STS72H60',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZnaShWtvY_c-jS-oMMj4M40pPogmwoXY',
    appId: '1:128483735486:android:1dcc36b24c4d1d6a6c2bef',
    messagingSenderId: '128483735486',
    projectId: 'eventhub-b088e',
    storageBucket: 'eventhub-b088e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIgOKz5pFBhFBabzsv10Is5dcmXw6hwog',
    appId: '1:128483735486:ios:8e1c9cee0b9fad996c2bef',
    messagingSenderId: '128483735486',
    projectId: 'eventhub-b088e',
    storageBucket: 'eventhub-b088e.appspot.com',
    iosBundleId: 'com.example.eventManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIgOKz5pFBhFBabzsv10Is5dcmXw6hwog',
    appId: '1:128483735486:ios:8e1c9cee0b9fad996c2bef',
    messagingSenderId: '128483735486',
    projectId: 'eventhub-b088e',
    storageBucket: 'eventhub-b088e.appspot.com',
    iosBundleId: 'com.example.eventManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZYlyW44h-2Y836hSHRArqq1EbDjh5-yM',
    appId: '1:128483735486:web:191f5d9d158a06d16c2bef',
    messagingSenderId: '128483735486',
    projectId: 'eventhub-b088e',
    authDomain: 'eventhub-b088e.firebaseapp.com',
    storageBucket: 'eventhub-b088e.appspot.com',
    measurementId: 'G-BZYS00KSCE',
  );
}
